spring:
  application:
    name: aop-demo

  config:
    activate:
      on-profile: "dev"

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        non_contextual_creation: true
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    spring.aop.demo: DEBUG
